### ISSUE TITLE
feat: dockerize all the things

### ISSUE THREAD

**Issue by vinnyA3** [vinnyA3/anime-series-dl#13]
## Description

Type: `Feature`

This would give the user a convenient way to run `animego-dl` and `yt-dlp` in an isolated environment.

## Tasks and User Stories

As a user, I would like to:
  * use docker to install node, `animego-dl` & `yt-dlp` in an isolated
    environment
  * be able to mount a directly into the container (so the tool can download to
    the host filesystem).

**Comment by DipayanP007** [comment]
Hey @vinnyA3 I can dockerize the project. But to run the person needs to exec into the container. Is that what you want? Or can you please explain it to me ?

**Comment by vinnyA3** [comment]
Hi @DipayanP007 !  That would be a great help!

As for the Docker integration, I believe this cli tool's current implementation
should be fine with a `CMD` / `ENTRYPOINT`, which will run the tool -- this way,
the container can run `animego-dl` as a one-off command.  What do you think
about this?

**Comment by vinnyA3** [comment]
Hi @DipayanP007 , awesome! 

Pretty much!  The command has a one-off execution, so I think running the container interactively should do the trick.  What do you think?

**Comment by DipayanP007** [comment]
Yeah It will work but the container will need a volume mount so that the downloaded anime are present in the local too. Is that okay?

**Comment by vinnyA3** [comment]
Perfect 👍   That sounds good to me.  When you are ready, I can assign the issue
to you !

**Comment by mayanknoldus** [comment]
Hi @vinnyA3. Could you please proviide me with your inputs on this.

**Comment by vinnyA3** [comment]
I left some comments @mayanknoldus :  https://github.com/vinnyA3/animego-dl/pull/19#issuecomment-1035901010 🙏🏽

**Comment by mayanknoldus** [comment]
Hi @vinnyA3. Have you had a chance to look into the latest changes made to the Dockerfile.
